import { useEffect, useRef, useState } from 'react';
import { Bot, Lightbulb, Send, Trash2, X } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { api, isAbortError } from '../../services/api';
import { PageHeader } from '../../components/ui';
import AssistantResponse, { safeAssistantBlocks } from '../../components/AssistantResponse';
import { useUserSessionState, userSessionIdentity } from '../../hooks/useUserSessionState';

function responseSource(response) {
  if (response.source === 'deterministic') return 'Deterministic MAWOS result';
  if (response.source === 'groq') return 'Generated by Groq AI';
  if (response.source === 'ollama') return 'Generated by local AI';
  if (response.source === 'safe_fallback') return 'Safe fallback';
  if (response.source_label === 'Deterministic answer'
    || response.source_label === 'AI-grounded record answer'
    || response.source_label === 'Library catalogue result'
    || response.source_label === 'Official MAWOS information') return 'Deterministic MAWOS result';
  if (response.source_label === 'General AI response'
    || response.source_label === 'Library-guided AI response') {
    return response.provider === 'groq' ? 'Generated by Groq AI' : 'Generated by local AI';
  }
  if (response.source_label) return response.source_label;
  if (response.mode === 'llm') {
    return response.fallback ? 'Safe fallback' : response.provider === 'groq'
      ? 'Generated by Groq AI' : 'Generated by local AI';
  }
  if (response.mode === 'scope') return 'Read-only assistant scope';
  const rejectedOllama = Boolean(
    response.fallback_code
    || response.fallback
    || response.routing?.deterministic_fallback,
  );
  return rejectedOllama ? 'Safe fallback' : 'Deterministic MAWOS result';
}

export default function AssistantPage() {
  const { token, user, checking } = useAuth();
  if (checking) return <AssistantLoading />;
  if (!token || !user) return null;
  const identity = userSessionIdentity(user);
  const accountKey = identity ? `${identity.identifier}:${identity.role}` : `unscoped:${user.role}`;
  return <AssistantConversation key={accountKey} token={token} user={user} accountKey={accountKey} />;
}

const SAFE_GENERAL_PROMPTS = ['What can you help me with?', 'What is MAWOS?'];
const ROLE_VALUES = new Set(['student', 'faculty', 'hod', 'principal', 'admin', 'parent', 'librarian']);
const MAX_STORED_MESSAGES = 50;
const MAX_CONTEXT_MESSAGES = 8;
const MAX_CONTEXT_CHARS = 4000;
const EMPTY_CONVERSATION = { messages: [], contextTopic: null, conversationContext: [] };
const MIN_THINKING_MS = 3000;
const minimumThinkingDelay = () => new Promise((resolve) => window.setTimeout(resolve, MIN_THINKING_MS));

function AssistantLoading() {
  return <main className="p-6"><p className="text-sm text-muted">Preparing your assistant…</p></main>;
}

function SuggestionGroups({ groups = [], fallback = false, busy, onSelect }) {
  const visibleGroups = fallback
    ? [...groups, { label: 'General help', prompts: SAFE_GENERAL_PROMPTS }]
    : groups;
  return <>{visibleGroups.map((group) => <div key={group.label}>
    <p className="mb-1 text-xs font-semibold text-muted">{group.label}</p>
    <div className="flex flex-wrap gap-2">{group.prompts.map((prompt) => <button
      key={prompt} type="button" disabled={busy} onClick={() => onSelect(prompt)}
      className="rounded-lg bg-slate-100 px-2 py-1 text-xs text-slate-700 hover:bg-blue-50"
    >{prompt}</button>)}</div>
  </div>)}</>;
}

function isCapabilityResponse(value, expectedRole) {
  return value && typeof value === 'object'
    && ROLE_VALUES.has(value.role) && value.role === expectedRole
    && ['title', 'subtitle', 'description', 'greeting', 'help', 'input_placeholder'].every(
      (key) => typeof value[key] === 'string')
    && Array.isArray(value.record_capabilities)
    && value.record_capabilities.every((item) => item && typeof item.category === 'string' && typeof item.scope === 'string')
    && Array.isArray(value.suggestion_groups)
    && value.suggestion_groups.every((group) => group && typeof group.label === 'string'
      && Array.isArray(group.prompts) && group.prompts.every((prompt) => typeof prompt === 'string'));
}

function errorKind(error) {
  if (['authentication', 'authorization', 'network', 'server', 'request'].includes(error?.category)) return error.category;
  return 'network';
}

function safeLibraryCandidates(value) {
  if (!Array.isArray(value)) return [];
  return value.filter((book) => book
    && typeof book.title === 'string' && book.title.length > 0 && book.title.length <= 240
    && typeof book.isbn === 'string' && /^[0-9Xx -]{1,32}$/.test(book.isbn)
    && typeof book.author === 'string' && book.author.length > 0 && book.author.length <= 240
    && typeof book.category === 'string' && book.category.length > 0 && book.category.length <= 120)
    .slice(0, 5).map(({ title, isbn, author, category }) => ({ title, isbn, author, category }));
}

function safeSuggestions(value) {
  if (!Array.isArray(value) || value.length < 2 || value.length > 4) return [];
  const suggestions = value.map((item) => typeof item === 'string' && item.trim().length > 0
    && item.length <= 160 ? item.trim() : null);
  return suggestions.every(Boolean) ? [...new Set(suggestions)].slice(0, 4) : [];
}

function safeTrace(value) {
  if (!value || typeof value !== 'object' || !['simple', 'collapsible'].includes(value.visibility)
    || typeof value.summary !== 'string' || !value.summary.trim() || value.summary.length > 200
    || typeof value.duration_ms !== 'number' || !Number.isFinite(value.duration_ms)
    || value.duration_ms < 0 || !Array.isArray(value.steps) || value.steps.length > 6) return null;
  const steps = value.steps.map((step) => step && typeof step.label === 'string' && step.label.length <= 80
    && typeof step.detail === 'string' && step.detail.length <= 200
    && ['complete', 'bypassed', 'safe_fallback'].includes(step.status)
    ? { label: step.label, detail: step.detail, status: step.status } : null);
  return steps.every(Boolean) ? {
    visibility: value.visibility, summary: value.summary, duration_ms: value.duration_ms, steps,
  } : null;
}

function safePresentation(response) {
  const hasStructuredContract = response && ['summary', 'blocks', 'suggestions', 'source'].some(
    (key) => Object.prototype.hasOwnProperty.call(response, key),
  );
  if (!hasStructuredContract) return {
    summary: response.text,
    blocks: [],
    suggestions: [],
    safeTrace: null,
    source: responseSource(response),
    malformed: false,
  };
  const summary = typeof response.summary === 'string' && response.summary.trim()
    && response.summary.length <= 1200 ? response.summary.trim() : null;
  const blocks = safeAssistantBlocks(response.blocks);
  const suggestions = safeSuggestions(response.suggestions);
  const source = ['deterministic', 'groq', 'ollama', 'safe_fallback'].includes(response.source)
    ? responseSource(response) : null;
  const trace = response.safe_trace == null ? null : safeTrace(response.safe_trace);
  if (!summary || blocks === null || suggestions.length < 2 || !source
    || (response.safe_trace != null && !trace)) {
    const fallback = 'The assistant returned an answer that could not be displayed safely. Please retry.';
    return {
      summary: fallback,
      blocks: [{ type: 'status_notice', title: 'Safe fallback',
        message: 'No unvalidated assistant content was shown.', status: 'warning' }],
      suggestions: ['Try that request again', 'What can you help me with?'],
      safeTrace: null,
      source: 'Safe fallback',
      malformed: true,
    };
  }
  return { summary, blocks, suggestions, safeTrace: trace, source, malformed: false };
}

function safeStoredMessage(message, role, index) {
  if (!message || message.role !== role || typeof message.text !== 'string'
    || !message.text.trim() || message.text.length > 12000) return null;
  const safe = { id: `stored-${index}`, role, text: message.text };
  if (role === 'agent') {
    if (typeof message.source === 'string' && message.source.length <= 100) safe.source = message.source;
    if (typeof message.note === 'string' && message.note.length <= 300) safe.note = message.note;
    if (Array.isArray(message.actions)) {
      safe.actions = message.actions.filter((action) => action
        && typeof action.label === 'string' && action.label.length <= 100
        && typeof action.route === 'string'
        && /^\/student\/library(?:\?q=[^\s]*)?$/.test(action.route)).slice(0, 5)
        .map(({ label, route }) => ({ label, route }));
    }
    if (Array.isArray(message.candidates)) {
      safe.candidates = safeLibraryCandidates(message.candidates);
    }
    if (message.candidateContext === true) safe.candidateContext = true;
    if (typeof message.summary === 'string' && message.summary.trim() && message.summary.length <= 1200) {
      const blocks = safeAssistantBlocks(message.blocks);
      const suggestions = safeSuggestions(message.suggestions);
      const trace = message.safeTrace == null ? null : safeTrace(message.safeTrace);
      if (blocks !== null && (!message.suggestions || suggestions.length >= 2)
        && (message.safeTrace == null || trace)) {
        safe.summary = message.summary;
        safe.blocks = blocks;
        safe.suggestions = suggestions;
        if (trace) safe.safeTrace = trace;
      }
    }
  }
  return safe;
}

function safeConversation(value) {
  if (!value || typeof value !== 'object' || !Array.isArray(value.messages)
    || !Array.isArray(value.conversationContext)) return null;
  const messages = [];
  let pendingUser = null;
  value.messages.forEach((message, index) => {
    if (message?.role === 'user') {
      pendingUser = safeStoredMessage(message, 'user', index);
    } else if (message?.role === 'agent' && pendingUser) {
      const agent = safeStoredMessage(message, 'agent', index);
      if (agent) messages.push(pendingUser, agent);
      pendingUser = null;
    }
  });
  const boundedMessages = messages.slice(-MAX_STORED_MESSAGES)
    .map((message, index) => ({ ...message, id: `stored-${index}` }));
  const conversationContext = [];
  for (let index = 0; index < value.conversationContext.length; index += 2) {
    const userMessage = value.conversationContext[index];
    const assistantMessage = value.conversationContext[index + 1];
    if (!userMessage || !assistantMessage || userMessage.role !== 'user'
      || assistantMessage.role !== 'assistant'
      || !['general_ai', 'library_catalogue'].includes(userMessage.category)
      || assistantMessage.category !== userMessage.category
      || typeof userMessage.content !== 'string' || typeof assistantMessage.content !== 'string'
      || !userMessage.content.trim() || !assistantMessage.content.trim()
      || userMessage.content.length > 700 || assistantMessage.content.length > 700
      || typeof assistantMessage.proof !== 'string'
      || !/^[0-9a-f]{64}$/.test(assistantMessage.proof)) return null;
    const safeUser = {
      role: 'user', category: userMessage.category, content: userMessage.content,
    };
    const safeAssistant = {
      role: 'assistant', category: assistantMessage.category, content: assistantMessage.content,
      proof: assistantMessage.proof,
    };
    if (assistantMessage.category === 'library_catalogue') {
      if (!Array.isArray(assistantMessage.books)) return null;
      safeAssistant.books = safeLibraryCandidates(assistantMessage.books);
      if (safeAssistant.books.length) {
        if (!Number.isInteger(assistantMessage.issued_at) || assistantMessage.issued_at < 0) return null;
        safeAssistant.issued_at = assistantMessage.issued_at;
      }
    }
    conversationContext.push(safeUser, safeAssistant);
  }
  const boundedContext = conversationContext.slice(-MAX_CONTEXT_MESSAGES);
  while (boundedContext.reduce((total, item) => total + item.content.length, 0) > MAX_CONTEXT_CHARS) {
    boundedContext.splice(0, 2);
  }
  const contextTopic = typeof value.contextTopic === 'string'
    && /^[a-z][a-z_]{0,39}$/.test(value.contextTopic) ? value.contextTopic : null;
  return { messages: boundedMessages, contextTopic, conversationContext: boundedContext };
}

function isStoredConversation(value) {
  const sanitized = safeConversation(value);
  return sanitized !== null && JSON.stringify(sanitized) === JSON.stringify(value);
}

function AssistantConversation({ token, user, accountKey }) {
  const [conversation, setConversation, clearStoredConversation] = useUserSessionState(
    user, 'assistant', EMPTY_CONVERSATION,
    { validate: isStoredConversation, serialize: safeConversation },
  );
  const contextTopic = useRef(conversation.contextTopic);
  const conversationContext = useRef(conversation.conversationContext);
  const pending = useRef(null);
  const capabilityRequest = useRef(null);
  const automaticRetryUsed = useRef(false);
  const submitting = useRef(false);
  const nextMessageId = useRef(0);
  const active = useRef(true);
  const [capability, setCapability] = useState(null);
  const [capabilityState, setCapabilityState] = useState({ status: 'loading', error: null });
  const messages = conversation.messages;
  const [retryVersion, setRetryVersion] = useState(0);
  useEffect(() => {
    let cancelled = false;
    const requestId = Symbol(accountKey);
    active.current = true;
    pending.current?.abort();
    const controller = new AbortController();
    capabilityRequest.current = { requestId, controller };
    setCapability(null);
    setCapabilityState({ status: 'loading', error: null });

    const load = async () => {
      try {
        const next = await api.assistantCapabilities(token, controller.signal);
        if (cancelled || capabilityRequest.current?.requestId !== requestId) return;
        if (!isCapabilityResponse(next, user.role)) {
          setCapabilityState({ status: 'error', error: 'malformed' });
          return;
        }
        setCapability(next);
        setConversation((current) => current.messages.length ? current : {
          ...current, messages: [{ id: `greeting-${accountKey}`, role: 'agent', text: next.greeting }],
        });
        setCapabilityState({ status: 'ready', error: null });
      } catch (error) {
        if (cancelled || isAbortError(error) || capabilityRequest.current?.requestId !== requestId) return;
        if (error?.category === 'authentication' && !automaticRetryUsed.current) {
          automaticRetryUsed.current = true;
          setRetryVersion((version) => version + 1);
          return;
        }
        setCapabilityState({ status: 'error', error: errorKind(error) });
      }
    };
    load();
    return () => {
      cancelled = true;
      active.current = false;
      controller.abort();
      pending.current?.abort();
    };
  }, [accountKey, retryVersion, token, user.role]);
  const [value, setValue] = useState('');
  const [busy, setBusy] = useState(false);
  const [suggestionsOpen, setSuggestionsOpen] = useState(false);
  const [loadingText, setLoadingText] = useState('Preparing your answer…');
  const chatScrollRef = useRef(null);
  useEffect(() => {
    const target = chatScrollRef.current?.lastElementChild;
    if (typeof target?.scrollIntoView === 'function') target.scrollIntoView({ block: 'end', behavior: 'smooth' });
  }, [messages, busy]);
  const append = (message) => setConversation((current) => ({
    messages: [
      ...current.messages.slice(-(MAX_STORED_MESSAGES - 1)),
      { ...message, id: message.id || `message-${++nextMessageId.current}` },
    ],
    contextTopic: contextTopic.current,
    conversationContext: conversationContext.current,
  }));

  const rememberCompletedPair = (question, response) => {
    const category = response.category;
    const isGeneral = category === 'general_ai' && response.mode === 'general_ai';
    const isLibrary = category === 'library_catalogue';
    if ((!isGeneral && !isLibrary) || !/^[0-9a-f]{64}$/.test(response.context_proof || '')) return;
    const userMessage = { role: 'user', category, content: question.slice(0, 700) };
    const assistantMessage = {
      role: 'assistant', category, content: response.text.slice(0, 700), proof: response.context_proof,
    };
    if (isLibrary) {
      assistantMessage.books = safeLibraryCandidates(response.context_books);
      if (assistantMessage.books.length) {
        if (!Number.isInteger(response.context_issued_at)) return;
        assistantMessage.issued_at = response.context_issued_at;
      }
    }
    const next = [...conversationContext.current, userMessage, assistantMessage]
      .slice(-MAX_CONTEXT_MESSAGES);
    while (next.reduce((total, item) => total + item.content.length, 0) > MAX_CONTEXT_CHARS) {
      next.splice(0, 2);
    }
    conversationContext.current = next;
  };

  const send = async (event, suggestedText = null) => {
    event?.preventDefault();
    const text = (suggestedText ?? value).trim();
    if (!text || busy || submitting.current || (capabilityState.status === 'loading')) return;
    submitting.current = true;
    append({ role: 'user', text });
    setValue('');
    setBusy(true);
    setLoadingText(/\b(my|owe)\b.*(attendance|fees|marks)|show my marks/i.test(text)
      ? 'Looking up your authorized records…' : 'Preparing your answer…');
    pending.current = new AbortController();
    try {
      const responseRequest = api.chat(
        token, text, pending.current.signal, contextTopic.current, conversationContext.current,
      );
      // Observe early rejection now; the user still receives it after the minimum thinking state.
      responseRequest.catch(() => {});
      await minimumThinkingDelay();
      const response = await responseRequest;
      if (!active.current) return;
      if (!response || typeof response.text !== 'string' || !response.mode || !response.routing) {
        throw new Error('Invalid assistant response');
      }
      const presentation = safePresentation(response);
      contextTopic.current = response.context_topic ?? null;
      if (!presentation.malformed) rememberCompletedPair(text, response);
      append({
        role: 'agent', text: presentation.malformed ? presentation.summary : response.text,
        summary: presentation.summary, blocks: presentation.blocks,
        suggestions: presentation.suggestions, safeTrace: presentation.safeTrace,
        source: presentation.source,
        candidates: safeLibraryCandidates(response.context_books),
        candidateContext: response.category === 'library_catalogue',
        actions: Array.isArray(response.actions) ? response.actions.filter(
          (action) => action && typeof action.label === 'string'
            && /^\/student\/library(?:\?q=[^\s]*)?$/.test(action.route),
        ) : [],
        note: response.mode === 'general_ai'
          ? 'Generated by AI and may contain mistakes. Verify important information.'
          : null,
      });
    } catch (error) {
      if (!active.current) return;
      if (import.meta.env.DEV) {
        // Deliberately log only a coarse category; messages, tokens and stack traces are private.
        console.warn('Assistant request failed', { category: errorKind(error) });
      }
      contextTopic.current = null;
      conversationContext.current = [];
      append({
        role: 'error',
        text: 'The assistant could not complete that request. Your records were not changed. Please try again.',
        retry: text,
      });
    } finally {
      submitting.current = false;
      if (active.current) setBusy(false);
    }
  };

  const retryCapabilities = () => {
    automaticRetryUsed.current = true;
    setRetryVersion((version) => version + 1);
  };
  const clearConversation = () => {
    if (!window.confirm('Clear this conversation for your current session?')) return;
    pending.current?.abort();
    submitting.current = false;
    setBusy(false);
    contextTopic.current = null;
    conversationContext.current = [];
    clearStoredConversation();
    setConversation({
      ...EMPTY_CONVERSATION,
      messages: capability?.greeting
        ? [{ id: `greeting-${accountKey}`, role: 'agent', text: capability.greeting }] : [],
    });
  };
  const capabilityFailed = capabilityState.status === 'error';
  const canUseChat = capabilityState.status === 'ready' || capabilityFailed;
  const currentCandidates = [...messages].reverse().find(
    (message) => message.role === 'agent' && message.candidateContext,
  )?.candidates || [];

  const chooseSuggestion = (prompt) => {
    setSuggestionsOpen(false);
    send(null, prompt);
  };

  return <>
    <div className="assistant-page-header"><PageHeader title={capability?.title || 'Academic assistant'} eyebrow="MAWOS / Role-scoped agent conversation">
      <p className="assistant-page-description mt-1 text-sm text-muted">{capability?.description || 'Loading your authorized assistant scope…'}</p>
    </PageHeader></div>
    <section className="assistant-shell card mx-auto flex max-w-4xl flex-col overflow-hidden p-0">
      <div className="flex items-center gap-3 border-b p-4">
        <span className="rounded-lg bg-blue-50 p-2 text-primary"><Bot size={20} /></span>
        <div className="min-w-0 flex-1"><p className="font-semibold">{capability?.title || 'Academic assistant'}</p><p className="text-xs text-muted">{capability?.subtitle || 'Loading authorized capabilities'}</p></div>
        <button type="button" className="assistant-clear btn-secondary !px-3" disabled={busy || !messages.some((message) => message.role === 'user')} onClick={clearConversation}><Trash2 size={16} /><span className="assistant-clear-label">Clear conversation</span></button>
      </div>
      <div ref={chatScrollRef} className="min-h-0 flex-1 space-y-4 overflow-auto p-4 sm:p-5" aria-live="polite">
        {capabilityState.status === 'loading' && <div aria-live="polite" className="text-sm text-muted">Loading your authorized assistant scope…</div>}
        {capabilityFailed && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Assistant capabilities are temporarily unavailable. You can still ask general academic or MAWOS questions.<button type="button" className="ml-2 font-semibold underline" onClick={retryCapabilities}>Retry</button></div>}
        {messages.map((message) => message.role === 'user'
          ? <div className="ml-auto w-fit max-w-[85%] whitespace-pre-wrap rounded-2xl rounded-tr-md bg-primary px-3 py-2 text-sm leading-6 text-white shadow-sm" key={message.id}>{message.text}</div>
          : message.role === 'error'
            ? <div className="max-w-[90%] rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert" key={message.id}><p>{message.text}</p>{message.retry && <button type="button" className="mt-2 font-semibold underline" onClick={() => setValue(message.retry)}>Retry this query</button>}</div>
            : message.source || message.summary
              ? <AssistantResponse message={message} role={user.role} onSuggestion={setValue} key={message.id} />
              : <div className="flex max-w-[90%] items-start gap-2" key={message.id}><span className="mt-1 shrink-0 rounded-lg bg-blue-50 p-2 text-primary"><Bot size={17} aria-hidden="true" /></span><div className="whitespace-pre-wrap rounded-2xl rounded-tl-md bg-slate-100 p-3 text-sm leading-6 text-slate-800">{message.text}</div></div>)}
        {busy && <div className="flex max-w-[90%] items-start gap-2" aria-label="MAWOS Assistant is thinking"><span className="mt-1 shrink-0 rounded-lg bg-blue-50 p-2 text-primary"><Bot size={17} aria-hidden="true" /></span><div className="rounded-2xl rounded-tl-md bg-slate-100 p-3 text-sm text-muted"><p className="mb-2">MAWOS Assistant is thinking…</p><span className="assistant-thinking-dots" aria-label={loadingText}><i /><i /><i /></span></div></div>}
      </div>
      <div className="space-y-3 border-t px-4 py-3">
        {currentCandidates.length > 1 && <div>
          <p className="mb-1 text-xs font-semibold text-muted">Follow up on these books</p>
          <div className="flex flex-wrap gap-2">{[
            'Which is best for a beginner?', 'Compare these books', 'Check availability',
          ].map((prompt) => <button key={prompt} type="button" disabled={busy}
            onClick={() => chooseSuggestion(prompt)} className="rounded-lg bg-blue-50 px-2 py-1 text-xs text-primary hover:bg-blue-100"
          >{prompt}</button>)}</div>
        </div>}
        <div className="assistant-hidden-suggestions"><SuggestionGroups groups={capability?.suggestion_groups} fallback={capabilityFailed} busy={busy} onSelect={setValue} /></div>
        <button type="button" className="assistant-suggestions-trigger btn-secondary w-full" aria-expanded={suggestionsOpen} aria-controls="assistant-suggestions" onClick={() => setSuggestionsOpen(true)} disabled={busy}>
          <Lightbulb size={17} />Suggestions
        </button>
      </div>
      <form className="assistant-composer flex min-w-0 gap-2 border-t p-4" onSubmit={send}>
        <label className="sr-only" htmlFor="chat">Ask a question</label>
        <input id="chat" className="field" disabled={!canUseChat} value={value} onChange={(event) => setValue(event.target.value)} placeholder={capability?.input_placeholder || (capabilityFailed ? 'Ask a general academic or MAWOS question…' : 'Loading authorized capabilities…')} />
        <button aria-label="Send message" className="btn-primary" disabled={busy || !canUseChat}><Send size={18} /></button>
      </form>
    </section>
    {suggestionsOpen && <div className="assistant-suggestions-sheet fixed inset-0 z-40 bg-slate-950/40 p-3" role="dialog" aria-modal="true" aria-labelledby="assistant-suggestions-title" onClick={() => setSuggestionsOpen(false)}>
      <section id="assistant-suggestions" className="max-h-[75dvh] w-full overflow-y-auto rounded-2xl bg-white p-4 pb-[calc(1rem+env(safe-area-inset-bottom))] shadow-xl sm:max-w-2xl" onClick={(event) => event.stopPropagation()}>
        <div className="mb-3 flex items-center justify-between gap-3"><div><h2 id="assistant-suggestions-title" className="font-semibold">Suggestions</h2><p className="text-xs text-muted">Choose a prompt to send.</p></div><button type="button" className="btn-secondary !min-h-0 !p-2" aria-label="Close suggestions" onClick={() => setSuggestionsOpen(false)}><X size={18} /></button></div>
        <div className="space-y-4"><SuggestionGroups groups={capability?.suggestion_groups} fallback={capabilityFailed} busy={busy} onSelect={chooseSuggestion} /></div>
      </section>
    </div>}
  </>;
}
