import { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../services/api';
import { useUserSessionState } from '../../hooks/useUserSessionState';

const empty = { name: '', provider: '', description: '', amount: 0, application_url: 'https://', opens_at: '', closes_at: '', official_document_reference: '', criteria: {} };
function State({ loading, error, children }) { return loading ? <p className="p-6 text-muted">Loading scholarships…</p> : error ? <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error.message}</p> : children; }
function Badge({ value }) { const color = value === 'ELIGIBLE' || value === 'PUBLISHED' ? 'bg-emerald-100 text-emerald-800' : value === 'NOT_ELIGIBLE' || value === 'REJECTED' ? 'bg-red-100 text-red-800' : value === 'UNABLE_TO_DETERMINE' ? 'bg-amber-100 text-amber-800' : value === 'ALREADY_APPLIED' ? 'bg-blue-100 text-blue-800' : 'bg-slate-100 text-slate-700'; const label = value === 'UNABLE_TO_DETERMINE' ? 'Information needed' : value?.replaceAll('_', ' '); return <span className={`inline-flex shrink-0 items-center rounded-full px-2.5 py-1 text-xs font-semibold uppercase tracking-wide ${color}`}>{label}</span>; }
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const date = value => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value));

export function StudentScholarships() {
  const { token, user } = useAuth(); const [data, setData] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [tab, setTab] = useUserSessionState(user, 'student-scholarship-tab', 'Recommended', { validate: value => ['Recommended', 'All available', 'Applied', 'Closed'].includes(value) });
  const load = () => { setLoading(true); api.scholarships(token, 'student').then(x => setData(x.scholarships || [])).catch(setError).finally(() => setLoading(false)); };
  useEffect(load, [token]); const filtered = data.filter(x => tab === 'Applied' ? x.application : tab === 'Closed' ? x.status === 'CLOSED' : tab === 'Recommended' ? x.eligibility_status === 'ELIGIBLE' : x.status !== 'CLOSED');
  return <section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Scholarships</h2><p className="text-sm text-muted">Your department scholarships and secure eligibility results.</p></div><div role="tablist" className="flex flex-wrap gap-2">{['Recommended','All available','Applied','Closed'].map(x => <button key={x} role="tab" aria-selected={tab === x} className={tab === x ? 'btn-primary' : 'btn-secondary'} onClick={() => setTab(x)}>{x}</button>)}</div></div><State loading={loading} error={error}>{!filtered.length ? <p className="rounded-lg border p-6 text-muted">No scholarships in this view.</p> : <div className="grid gap-4 md:grid-cols-2">{filtered.map(s => <article key={s.id} className="flex min-w-0 flex-col rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-bold">{s.name}</h3><p className="mt-1 text-sm text-muted">{s.provider} · {money(s.amount)}</p></div><Badge value={s.application ? 'ALREADY_APPLIED' : s.eligibility_status || s.status} /></div><p className="mt-3 line-clamp-3 text-sm">{s.description}</p><p className="mt-3 text-sm text-muted">Deadline: {date(s.closes_at)}</p>{s.reason_codes?.length ? <p className="mt-2 text-sm text-muted">{s.reason_codes.join(', ').replaceAll('_', ' ')}</p> : null}<div className="mt-4"><a className="btn-secondary inline-block" href={s.application_url} target="_blank" rel="noreferrer">Official application</a></div></article>)}</div>}</State></section>;
}

export function FacultyScholarships() {
  const { token, user } = useAuth(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [form, setForm] = useState(empty); const [busy, setBusy] = useState(false);
  const load = () => { setLoading(true); api.scholarships(token, 'faculty').then(x => setItems(x.scholarships || [])).catch(setError).finally(() => setLoading(false)); }; useEffect(load, [token]);
  const submit = async e => { e.preventDefault(); setBusy(true); setError(null); try { await api.saveScholarship(token, null, { ...form, department_code: user.dept, opens_at: new Date(form.opens_at).toISOString(), closes_at: new Date(form.closes_at).toISOString(), amount: Number(form.amount) }); setForm(empty); load(); } catch (x) { setError(x); } finally { setBusy(false); } };
  const action = async (id, name) => { setBusy(true); try { await api.scholarshipAction(token, `/faculty/scholarships/${id}/${name}`); load(); } catch (x) { setError(x); } finally { setBusy(false); } };
  return <section><h2 className="text-xl font-bold">Scholarship Management</h2><p className="mb-5 text-sm text-muted">Create a draft, set structured criteria, and submit it to your HOD.</p><form onSubmit={submit} className="mb-6 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-2"><h3 className="font-semibold md:col-span-2">1. Basic information · 2. Eligibility · 3. Documents · 4. Review</h3>{[['name','Name'],['provider','Provider'],['amount','Amount'],['application_url','Official application URL'],['opens_at','Opens at'],['closes_at','Closes at']].map(([key,label]) => <label key={key} className="text-sm">{label}<input required={key !== 'amount'} type={key.includes('_at') ? 'datetime-local' : key === 'amount' ? 'number' : 'text'} className="field mt-1 w-full" value={form[key]} onChange={e => setForm({...form,[key]:e.target.value})} /></label>)}<label className="text-sm md:col-span-2">Description<textarea className="field mt-1 w-full" value={form.description} onChange={e => setForm({...form,description:e.target.value})} /></label><button disabled={busy} className="btn-primary w-fit">{busy ? 'Saving…' : 'Save draft'}</button></form><State loading={loading} error={error}>{!items.length ? <p className="text-muted">No scholarship drafts yet.</p> : <div className="space-y-3">{items.map(s => <div key={s.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-white p-4"><span><b>{s.name}</b> <span className="text-sm text-muted">{s.provider}</span></span><div className="flex items-center gap-2"><Badge value={s.status}/>{s.status === 'DRAFT' && <button disabled={busy} className="btn-secondary" onClick={() => action(s.id,'submit')}>Submit</button>}{s.status === 'PENDING_APPROVAL' && <button disabled={busy} className="btn-secondary" onClick={() => action(s.id,'withdraw')}>Withdraw</button>}</div></div>)}</div>}</State></section>;
}

export function HodScholarships() {
  const { token } = useAuth(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [refreshError, setRefreshError] = useState(null); const [actionError, setActionError] = useState(null); const [busyId, setBusyId] = useState(null);
  const load = async () => { setLoading(true); try { const result = await api.scholarships(token, 'hod'); setItems(result.scholarships || []); setRefreshError(null); return true; } catch (error) { setRefreshError(error); return false; } finally { setLoading(false); } };
  useEffect(() => { load(); }, [token]);
  const review = async (id, action) => { const comment = action === 'approve' ? '' : window.prompt(action === 'reject' ? 'Reason for rejection' : 'Requested changes') || ''; if (action !== 'approve' && !comment.trim()) return; setBusyId(id); setActionError(null); try { await api.scholarshipAction(token, `/hod/scholarships/${id}/${action}`, { comment }); if (!await load()) setActionError(new Error('The approval was saved, but the list could not be refreshed. Please reload this page.')); } catch (error) { setActionError(error); } finally { setBusyId(null); } };
  return <section><h2 className="text-xl font-bold">Scholarship Approvals</h2><p className="mb-5 text-sm text-muted">Department-only review; aggregate impact never exposes student identities.</p>{actionError && <p role="alert" className="mb-3 rounded-lg bg-red-50 p-4 text-red-700">{actionError.message}</p>}{refreshError && <p role="alert" className="mb-3 rounded-lg bg-amber-50 p-4 text-amber-800">Unable to refresh scholarships: {refreshError.message}</p>}{loading && !items.length ? <p className="p-6 text-muted">Loading scholarships…</p> : !items.length ? <p className="text-muted">No department scholarships.</p> : <div className="space-y-3">{items.map(s => <article key={s.id} className="rounded-lg border bg-white p-4"><div className="flex justify-between"><b>{s.name}</b><Badge value={s.status}/></div><p className="mt-2 text-sm">Impact: {s.impact?.total_applicable_students || 0} applicable · {s.impact?.eligible || 0} eligible · {s.impact?.not_eligible || 0} not eligible · {s.impact?.unable_to_determine || 0} missing data</p>{s.status === 'PENDING_APPROVAL' && <div className="mt-3 flex gap-2"><button disabled={busyId !== null} className="btn-secondary" onClick={() => review(s.id,'request-changes')}>Request changes</button><button disabled={busyId !== null} className="btn-secondary" onClick={() => review(s.id,'reject')}>Reject</button><button disabled={busyId !== null} className="btn-primary" onClick={() => review(s.id,'approve')}>{busyId === s.id ? 'Approving…' : 'Approve and publish'}</button></div>}</article>)}</div>}</section>;
}
