"""Strict structured Operations Assistant response tests."""
import asyncio
import json

import pytest
from pydantic import TypeAdapter, ValidationError

from backend.app import ai_provider, llm
from backend.app.api.schemas import AssistantBlock, ChatResponse
from backend.app.assistant_response import structure_response
from backend.app.models import User


ROUTING = {
    "tier": "lexicon", "margin": 1.0, "tau": 0.0, "escalated": False,
    "attempted_llm": False, "accepted_llm": False,
    "deterministic_fallback": False, "reason": "deterministic test",
    "fallback_from": None,
}


def result(intent, data, **overrides):
    value = {
        "text": "Authorized result", "category": "personal_record",
        "source_label": "Deterministic answer", "mode": "lexicon",
        "routing": ROUTING, "intent": intent, "data": data,
        "tools_used": [{"name": "authorized_read", "args": {}, "ms": 1.0}],
    }
    value.update(overrides)
    return value


def test_attendance_has_conclusion_metrics_typed_summary_and_table():
    response = structure_response(result("get_my_attendance", {
        "overall_pct": 72.5,
        "subjects": [
            {"subject": "Machine Learning (23AI51)", "attended": 18,
             "held": 25, "pct": 72, "shortage": True},
            {"subject": "DBMS (23AI52)", "attended": 22,
             "held": 25, "pct": 88, "shortage": False},
        ],
    }), role="student", duration_ms=4.2)
    assert response["source"] == "deterministic"
    assert "72.5%" in response["summary"]
    assert [block["type"] for block in response["blocks"]] == [
        "metric_cards", "attendance_summary", "table"]
    assert response["blocks"][0]["cards"][3]["value"] == "1"
    assert response["blocks"][2]["rows"][0]["subject_code"] == "23AI51"
    assert response["safe_trace"]["visibility"] == "simple"
    assert response["safe_trace"]["steps"] == []


def test_placement_and_library_cards_contain_only_safe_display_fields():
    placement = structure_response(result("get_my_placements", {"drives": [{
        "company": "Example Corp", "role": "Engineer", "package_lpa": 8,
        "date": "2026-10-01", "application_deadline": "2026-09-25",
        "application_url": "https://careers.example.com/apply", "eligible": True,
        "status": "OPEN", "internal_id": 991,
    }]}), role="student", duration_ms=3)
    card = next(block for block in placement["blocks"] if block["type"] == "placement_cards")["cards"][0]
    assert card["apply_url"] == "https://careers.example.com/apply"
    assert "internal_id" not in json.dumps(placement["blocks"])

    library = structure_response(result("search_library_catalogue", {"books": [{
        "title": "Python Crash Course", "author": "Eric Matthes", "category": "Python",
        "available_copies": 4, "total_copies": 6, "availability_status": "available",
        "isbn": "9780000000101", "borrower_id": 123,
    }], "database_url": "postgresql://secret"}, category="library_catalogue"),
        role="student", duration_ms=2)
    book = next(block for block in library["blocks"] if block["type"] == "library_book_cards")["books"][0]
    assert book["available_copies"] == 4
    assert "borrower_id" not in json.dumps(library["blocks"])
    assert "postgresql" not in json.dumps(library["blocks"])


def test_general_ai_is_plain_blocks_and_honestly_labelled():
    response = structure_response(result("general_ai", {},
        text="<script>bad()</script> Binary search halves the range.\n- Compare the middle item\n- Repeat",
        category="general_ai", source_label="Generated by Groq AI", mode="general_ai",
        provider="groq", tools_used=[], routing={**ROUTING, "tier": "llm", "escalated": True,
                                                 "attempted_llm": True, "accepted_llm": True}),
        role="faculty", duration_ms=12)
    assert response["source"] == "groq"
    assert "<script" not in json.dumps(response["blocks"])
    assert {block["type"] for block in response["blocks"]} == {"text", "bullet_list"}
    assert response["safe_trace"]["visibility"] == "collapsible"
    serialized_trace = json.dumps(response["safe_trace"]).lower()
    assert all(secret not in serialized_trace for secret in (
        "database_url", "jwt", "api_key", "system prompt", "tool arguments"))


def test_all_block_types_are_strict_and_malformed_blocks_are_rejected():
    blocks = [
        {"type": "text", "content": "Explanation"},
        {"type": "metric_cards", "cards": [{"label": "Count", "value": "1"}]},
        {"type": "table", "caption": "Results", "columns": [{"key": "name", "label": "Name"}], "rows": [{"name": "A"}]},
        {"type": "bullet_list", "items": ["One"]},
        {"type": "status_notice", "title": "Status", "message": "Ready", "status": "success"},
        {"type": "empty_state", "title": "Empty", "message": "Nothing here"},
        {"type": "link_action", "label": "Open", "url": "/student/library"},
        {"type": "warning", "title": "Warning", "message": "Check this"},
        {"type": "placement_cards", "cards": [{"company": "A", "role": "B", "eligibility": "Eligible"}]},
        {"type": "library_book_cards", "books": [{"title": "A", "author": "B", "category": "C", "available_copies": 1, "availability": "Available"}]},
        {"type": "event_cards", "events": [{"title": "A", "date": "2026-09-18"}]},
        {"type": "timetable", "entries": [{"day": "Monday", "period": "1", "subject": "DBMS"}]},
        {"type": "marks_summary", "subjects": [{"subject_code": "23AI51", "subject_name": "ML", "internals": {"CIE-1": 20}}]},
        {"type": "attendance_summary", "overall_percentage": 80, "subjects": []},
    ]
    adapter = TypeAdapter(list[AssistantBlock])
    assert len(adapter.validate_python(blocks)) == 14
    with pytest.raises(ValidationError):
        adapter.validate_python([{"type": "html", "content": "<b>unsafe</b>"}])
    with pytest.raises(ValidationError):
        adapter.validate_python([{"type": "table", "caption": "Bad", "columns": [
            {"key": "name", "label": "Name"}], "rows": [{"secret": "value"}]}])
    with pytest.raises(ValidationError):
        ChatResponse.model_validate({"summary": "x", "blocks": [], "suggestions": ["a", "b"],
                                     "source": "deterministic", "intent": "x", "unexpected": True})


def test_scholarship_and_notifications_are_deterministic(agents, db, monkeypatch):
    async def forbidden(*_args, **_kwargs):
        raise AssertionError("deterministic request reached an AI provider")

    monkeypatch.setattr(llm, "chat_async", forbidden)
    monkeypatch.setattr(llm, "general_chat_async", forbidden)
    monkeypatch.setattr(ai_provider, "_groq_request", forbidden)
    user = db.query(User).filter_by(username="4MT23AI001").one()
    for question, expected in (("show my scholarship status", "get_my_scholarship_status"),
                               ("show my notifications", "get_my_notifications")):
        response = asyncio.run(agents["orchestrator_agent"].handle_chat(db, user, question))
        assert response["intent"] == expected
        assert response["source"] == "deterministic"
        assert response["routing"]["attempted_llm"] is False
