"""Explicit response contracts for MAWOS API surfaces."""
import datetime as dt
from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


ChatTopic = Literal[
    "attendance", "fees", "marks", "eligibility", "greeting", "thanks", "identity",
    "help", "attendance_meaning", "attendance_requirement", "cie",
    "eligibility_meaning", "fees_meaning", "improve_attendance", "mawos", "reason_codes",
    "profile", "rag",
]
ChatCategory = Literal[
    "personal_record", "conversation", "institutional_faq", "clarification",
    "unsupported", "sensitive_or_disallowed", "general_ai", "department_record",
    "library_catalogue",
]
ChatSource = Literal[
    "Deterministic answer", "AI-grounded record answer", "General AI response",
    "Official MAWOS information", "Safe fallback", "Clarification",
    "Library catalogue result", "Library-guided AI response",
    "Generated by Groq AI", "Generated by local AI", "Deterministic MAWOS result",
]

AssistantSource = Literal["deterministic", "groq", "ollama", "safe_fallback"]
BlockTone = Literal["neutral", "info", "success", "warning", "danger"]
CellValue = str | int | float | bool | None


class StrictAssistantModel(BaseModel):
    """Closed response DTO; provider text can never add UI capabilities."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, allow_inf_nan=False)


class TextBlock(StrictAssistantModel):
    type: Literal["text"]
    heading: str | None = Field(default=None, max_length=120)
    content: str = Field(min_length=1, max_length=6000)


class MetricCard(StrictAssistantModel):
    label: str = Field(min_length=1, max_length=80)
    value: str = Field(min_length=1, max_length=80)
    detail: str | None = Field(default=None, max_length=160)
    tone: BlockTone = "neutral"


class MetricCardsBlock(StrictAssistantModel):
    type: Literal["metric_cards"]
    title: str | None = Field(default=None, max_length=120)
    cards: list[MetricCard] = Field(min_length=1, max_length=8)


class TableColumn(StrictAssistantModel):
    key: str = Field(pattern=r"^[a-z][a-z0-9_]{0,39}$")
    label: str = Field(min_length=1, max_length=80)


class TableBlock(StrictAssistantModel):
    type: Literal["table"]
    title: str | None = Field(default=None, max_length=120)
    caption: str = Field(min_length=1, max_length=240)
    columns: list[TableColumn] = Field(min_length=1, max_length=12)
    rows: list[dict[str, CellValue]] = Field(default_factory=list, max_length=100)

    @model_validator(mode="after")
    def rows_match_columns(self):
        keys = [column.key for column in self.columns]
        if len(keys) != len(set(keys)):
            raise ValueError("table column keys must be unique")
        allowed = set(keys)
        if any(set(row) - allowed for row in self.rows):
            raise ValueError("table rows contain undeclared columns")
        return self


class BulletListBlock(StrictAssistantModel):
    type: Literal["bullet_list"]
    title: str | None = Field(default=None, max_length=120)
    items: list[str] = Field(min_length=1, max_length=20)


class StatusNoticeBlock(StrictAssistantModel):
    type: Literal["status_notice"]
    title: str = Field(min_length=1, max_length=120)
    message: str = Field(min_length=1, max_length=1000)
    status: Literal["info", "success", "warning", "error"] = "info"


class EmptyStateBlock(StrictAssistantModel):
    type: Literal["empty_state"]
    title: str = Field(min_length=1, max_length=120)
    message: str = Field(min_length=1, max_length=600)


class LinkActionBlock(StrictAssistantModel):
    type: Literal["link_action"]
    label: str = Field(min_length=1, max_length=100)
    url: str = Field(min_length=1, max_length=2048)
    description: str | None = Field(default=None, max_length=240)
    external: bool = False

    @field_validator("url")
    @classmethod
    def safe_link(cls, value: str) -> str:
        import ipaddress
        from urllib.parse import urlsplit

        if any(character.isspace() or ord(character) < 32 for character in value):
            raise ValueError("link contains unsupported characters")
        if value.startswith("/") and not value.startswith("//") and "\\" not in value:
            return value
        parsed = urlsplit(value)
        if (parsed.scheme not in {"http", "https"} or not parsed.hostname
                or parsed.username or parsed.password):
            raise ValueError("link must be an app-relative or HTTP(S) URL without credentials")
        host = parsed.hostname.rstrip(".").lower()
        if host in {"localhost", "localhost.localdomain"} or host.endswith(".local"):
            raise ValueError("link must not target an internal host")
        try:
            address = ipaddress.ip_address(host)
        except ValueError:
            address = None
        if address is not None and not address.is_global:
            raise ValueError("link must not target an internal host")
        return value


class WarningBlock(StrictAssistantModel):
    type: Literal["warning"]
    title: str = Field(min_length=1, max_length=120)
    message: str = Field(min_length=1, max_length=1000)


class PlacementCard(StrictAssistantModel):
    company: str = Field(min_length=1, max_length=128)
    role: str = Field(min_length=1, max_length=128)
    package: str | None = Field(default=None, max_length=80)
    date: str | None = Field(default=None, max_length=80)
    deadline: str | None = Field(default=None, max_length=80)
    eligibility: str = Field(min_length=1, max_length=120)
    status: str | None = Field(default=None, max_length=80)
    apply_url: str | None = Field(default=None, max_length=2048)

    @field_validator("apply_url")
    @classmethod
    def safe_apply_link(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return LinkActionBlock(type="link_action", label="Apply", url=value, external=True).url


class PlacementCardsBlock(StrictAssistantModel):
    type: Literal["placement_cards"]
    title: str | None = Field(default=None, max_length=120)
    cards: list[PlacementCard] = Field(min_length=1, max_length=20)


class LibraryBookCard(StrictAssistantModel):
    title: str = Field(min_length=1, max_length=240)
    author: str = Field(min_length=1, max_length=240)
    category: str = Field(min_length=1, max_length=120)
    available_copies: int = Field(ge=0)
    total_copies: int | None = Field(default=None, ge=0)
    availability: str = Field(min_length=1, max_length=80)
    isbn: str | None = Field(default=None, max_length=32)


class LibraryBookCardsBlock(StrictAssistantModel):
    type: Literal["library_book_cards"]
    title: str | None = Field(default=None, max_length=120)
    books: list[LibraryBookCard] = Field(min_length=1, max_length=20)


class EventCard(StrictAssistantModel):
    title: str = Field(min_length=1, max_length=240)
    date: str = Field(min_length=1, max_length=80)
    time: str | None = Field(default=None, max_length=80)
    venue: str | None = Field(default=None, max_length=160)
    organizer: str | None = Field(default=None, max_length=160)
    description: str | None = Field(default=None, max_length=1000)


class EventCardsBlock(StrictAssistantModel):
    type: Literal["event_cards"]
    title: str | None = Field(default=None, max_length=120)
    events: list[EventCard] = Field(min_length=1, max_length=30)


class TimetableEntry(StrictAssistantModel):
    day: str = Field(min_length=1, max_length=40)
    period: str = Field(min_length=1, max_length=80)
    subject: str = Field(min_length=1, max_length=160)
    time: str | None = Field(default=None, max_length=80)
    room: str | None = Field(default=None, max_length=80)
    faculty: str | None = Field(default=None, max_length=160)


class TimetableBlock(StrictAssistantModel):
    type: Literal["timetable"]
    title: str | None = Field(default=None, max_length=120)
    entries: list[TimetableEntry] = Field(min_length=1, max_length=100)


class MarkSubject(StrictAssistantModel):
    subject_code: str = Field(min_length=1, max_length=40)
    subject_name: str = Field(min_length=1, max_length=160)
    internals: dict[str, float] = Field(default_factory=dict, max_length=10)
    cie_average: float | None = None


class MarksSummaryBlock(StrictAssistantModel):
    type: Literal["marks_summary"]
    title: str | None = Field(default=None, max_length=120)
    subjects: list[MarkSubject] = Field(min_length=1, max_length=50)


class AttendanceSubject(StrictAssistantModel):
    subject_code: str = Field(min_length=1, max_length=40)
    subject_name: str = Field(min_length=1, max_length=160)
    attended: int = Field(ge=0)
    total: int = Field(ge=0)
    percentage: float = Field(ge=0, le=100)
    status: Literal["On track", "Below threshold"]


class AttendanceSummaryBlock(StrictAssistantModel):
    type: Literal["attendance_summary"]
    overall_percentage: float = Field(ge=0, le=100)
    threshold_percentage: float = Field(default=75, ge=0, le=100)
    subjects: list[AttendanceSubject] = Field(default_factory=list, max_length=50)


AssistantBlock = Annotated[Union[
    TextBlock, MetricCardsBlock, TableBlock, BulletListBlock, StatusNoticeBlock,
    EmptyStateBlock, LinkActionBlock, WarningBlock, PlacementCardsBlock,
    LibraryBookCardsBlock, EventCardsBlock, TimetableBlock, MarksSummaryBlock,
    AttendanceSummaryBlock,
], Field(discriminator="type")]


class SafeTraceStep(StrictAssistantModel):
    label: str = Field(min_length=1, max_length=80)
    detail: str = Field(min_length=1, max_length=200)
    status: Literal["complete", "bypassed", "safe_fallback"] = "complete"


class SafeTrace(StrictAssistantModel):
    visibility: Literal["simple", "collapsible"]
    summary: str = Field(min_length=1, max_length=200)
    steps: list[SafeTraceStep] = Field(default_factory=list, max_length=6)
    duration_ms: float = Field(ge=0)


class NotificationItemResponse(BaseModel):
    id: int
    title: str
    message: str
    notification_type: str
    route: str | None = None
    related_entity_type: str | None = None
    related_entity_id: str | None = None
    source_agent: str
    created_at: dt.datetime
    at: dt.datetime
    read: bool
    read_at: dt.datetime | None = None


class NotificationListResponse(BaseModel):
    notifications: list[NotificationItemResponse] = Field(default_factory=list)
    unread_count: int = 0


class ParentChildResponse(BaseModel):
    usn: str
    name: str
    department: str
    year: int
    semester: int
    section: str
    relationship: str | None = None
    is_primary: bool | None = None
    mapping_id: int | None = None
    active: bool | None = None


class ParentProfileResponse(BaseModel):
    id: int
    name: str
    email: str | None = None
    mobile: str | None = None
    children: list[ParentChildResponse] = Field(default_factory=list)


class GeneratedCredentialsResponse(BaseModel):
    username: str
    temporary_password: str


class AdminParentResponse(BaseModel):
    id: int
    full_name: str
    username: str
    email: str | None = None
    mobile: str | None = None
    active: bool
    created_at: dt.datetime
    students: list[ParentChildResponse] = Field(default_factory=list)
    generated_credentials: GeneratedCredentialsResponse | None = None


class AdminParentListResponse(BaseModel):
    parents: list[AdminParentResponse] = Field(default_factory=list)
    total: int = 0


class ParentDashboardResponse(BaseModel):
    library: dict[str, Any] = Field(default_factory=dict)
    child: ParentChildResponse
    attendance: dict[str, Any] = Field(default_factory=dict)
    marks: dict[str, Any] = Field(default_factory=dict)
    fees: dict[str, Any] = Field(default_factory=dict)
    exams: dict[str, Any] = Field(default_factory=dict)
    timetable: dict[str, Any] = Field(default_factory=dict)
    scholarship: dict[str, Any] = Field(default_factory=dict)
    placements: list[dict[str, Any]] = Field(default_factory=list)
    events: list[dict[str, Any]] = Field(default_factory=list)


class ChatRoutingResponse(BaseModel):
    """Routing outcome; ``escalated`` is the legacy attempted-LLM flag."""
    tier: Literal["lexicon", "llm", "scope"]
    margin: float
    tau: float
    escalated: bool
    attempted_llm: bool = False
    accepted_llm: bool = False
    deterministic_fallback: bool = False
    reason: str
    fallback_from: str | None = None


class ChatToolUseResponse(BaseModel):
    name: str
    args: dict[str, Any] = Field(default_factory=dict)
    ms: float = 0.0


class ChatActionResponse(BaseModel):
    label: str
    route: str = Field(pattern=r"^/student/library(?:\?q=[^\s]*)?$")


class ChatLibraryContextBookResponse(BaseModel):
    title: str
    isbn: str
    author: str
    category: str


class ChatResponse(BaseModel):
    """Canonical read-only assistant result returned by ``POST /api/chat``."""
    model_config = ConfigDict(extra="forbid")

    # Structured, display-safe response contract. ``text`` and ``source_label``
    # remain below for bounded conversation context and older clients.
    summary: str = Field(min_length=1, max_length=1200)
    blocks: list[AssistantBlock] = Field(max_length=20)
    suggestions: list[str] = Field(min_length=2, max_length=4)
    source: AssistantSource
    safe_trace: SafeTrace | None = None
    refresh_required: bool = False
    text: str
    category: ChatCategory
    source_label: ChatSource
    context_topic: ChatTopic | None = None
    knowledge_sources: list[str] = Field(default_factory=list)
    mode: Literal["lexicon", "llm", "scope", "general_ai"]
    routing: ChatRoutingResponse
    tools_used: list[ChatToolUseResponse] = Field(default_factory=list)
    intent: str
    model: str | None = None
    provider: Literal["groq", "ollama"] | None = None
    latency_ms: float = 0.0
    fallback: bool = False
    fallback_code: str | None = None
    provenance: dict[str, Any] | None = None
    # Retained for compatibility with existing lexicon callers. It is always
    # the same authorized, read-only result used to produce ``text``.
    data: dict[str, Any] | None = None
    actions: list[ChatActionResponse] = Field(default_factory=list)
    # Safe public references only. Stock and other facts are always refreshed
    # server-side before a follow-up answer is produced.
    context_books: list[ChatLibraryContextBookResponse] = Field(default_factory=list)
    context_proof: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    context_issued_at: int | None = Field(default=None, ge=0)


class AssistantRecordCapabilityResponse(BaseModel):
    category: str
    scope: str


class AssistantSuggestionGroupResponse(BaseModel):
    label: str
    prompts: list[str] = Field(default_factory=list)


class AssistantCapabilitiesResponse(BaseModel):
    """Display-safe assistant scope derived from backend authorization."""
    role: Literal["student", "faculty", "hod", "principal", "admin", "parent", "librarian"]
    title: str
    subtitle: str
    description: str
    greeting: str
    help: str
    input_placeholder: str
    record_capabilities: list[AssistantRecordCapabilityResponse] = Field(default_factory=list)
    suggestion_groups: list[AssistantSuggestionGroupResponse] = Field(default_factory=list)
    ai_provider_mode: Literal["auto", "groq", "ollama", "disabled"] = "auto"
    ai_provider_status: str = "not_checked"
    ai_provider: Literal["groq", "ollama"] | None = None


class DepartmentAnalyticsResponse(BaseModel):
    dept: str
    students: int = 0
    faculty: int = 0
    shortage_students: int = 0
    avg_attendance: float = 0.0
    avg_cgpa: float = 0.0
    by_year: dict[int, int] = Field(default_factory=dict)


class DepartmentFeeCollectionResponse(BaseModel):
    due: float = 0.0
    collected: float = 0.0
    pct: float = 0.0


class FeeCollectionResponse(BaseModel):
    total_due: float = 0.0
    total_collected: float = 0.0
    total_outstanding: float = 0.0
    by_department: dict[str, DepartmentFeeCollectionResponse] = Field(
        default_factory=dict)


class PlacementStatsResponse(BaseModel):
    upcoming_drives: int = 0
    eligible_finalists: int = 0
    eligible_finalists_by_dept: dict[str, int] = Field(default_factory=dict)


class DepartmentAdmissionsResponse(BaseModel):
    intake: int = 0
    applications: int = 0
    allotted: int = 0


class AdmissionsFunnelResponse(BaseModel):
    stages: dict[str, int] = Field(default_factory=dict)
    departments: dict[str, DepartmentAdmissionsResponse] = Field(default_factory=dict)


class PrincipalAnalyticsResponse(BaseModel):
    departments: list[DepartmentAnalyticsResponse] = Field(default_factory=list)
    fee_collection: FeeCollectionResponse = Field(default_factory=FeeCollectionResponse)
    placements: PlacementStatsResponse = Field(default_factory=PlacementStatsResponse)
    admissions: AdmissionsFunnelResponse = Field(default_factory=AdmissionsFunnelResponse)


class AdmissionApplicationResponse(BaseModel):
    id: int
    applicant_name: str
    dept_code: str
    category: str
    tenth_pct: float
    twelfth_pct: float
    entrance_score: float
    status: str
    merit_score: float | None = None
    merit_rank: int | None = None
    allotted_usn: str | None = None
    notes: str = ""


class AdminAdmissionsResponse(BaseModel):
    funnel: AdmissionsFunnelResponse = Field(default_factory=AdmissionsFunnelResponse)
    applications: list[AdmissionApplicationResponse] = Field(default_factory=list)


class ScholarshipCriteriaRequest(BaseModel):
    minimum_cgpa: float | None = Field(None, ge=0, le=10)
    minimum_attendance: float | None = Field(None, ge=0, le=100)
    maximum_backlogs: int | None = Field(None, ge=0)
    fee_clearance_required: bool | None = None
    income_limit: float | None = Field(None, ge=0)
    allowed_departments: list[str] | None = None
    allowed_semesters: list[int] | None = None
    allowed_categories: list[str] | None = None
    required_documents: list[str] | None = None


class ScholarshipRequest(BaseModel):
    name: str = Field(min_length=2, max_length=160)
    provider: str = Field(min_length=2, max_length=160)
    description: str = Field(default="", max_length=5000)
    amount: float = Field(ge=0)
    application_url: str = Field(min_length=8, max_length=512)
    opens_at: dt.datetime
    closes_at: dt.datetime
    department_code: str = Field(min_length=2, max_length=8)
    official_document_reference: str = Field(default="", max_length=512)
    criteria: ScholarshipCriteriaRequest = Field(default_factory=ScholarshipCriteriaRequest)


class ScholarshipReviewRequest(BaseModel):
    comment: str = Field(default="", max_length=2000)


class ScholarshipApplyRequest(BaseModel):
    external_reference: str = Field(default="", max_length=256)
