"""Explicit response contracts for MAWOS API surfaces."""
import datetime as dt
from typing import Any, Literal

from pydantic import BaseModel, Field


ChatTopic = Literal[
    "attendance", "fees", "marks", "eligibility", "greeting", "thanks", "identity",
    "help", "attendance_meaning", "attendance_requirement", "cie",
    "eligibility_meaning", "fees_meaning", "improve_attendance", "mawos", "reason_codes",
    "profile", "rag",
]
ChatCategory = Literal[
    "personal_record", "conversation", "institutional_faq", "clarification",
    "unsupported", "sensitive_or_disallowed", "general_ai", "department_record",
    "library_catalogue",
]
ChatSource = Literal[
    "Deterministic answer", "AI-grounded record answer", "General AI response",
    "Official MAWOS information", "Safe fallback", "Clarification",
    "Library catalogue result", "Library-guided AI response",
    "Generated by Groq AI", "Generated by local AI", "Deterministic MAWOS result",
]


class NotificationItemResponse(BaseModel):
    id: int
    title: str
    message: str
    notification_type: str
    route: str | None = None
    related_entity_type: str | None = None
    related_entity_id: str | None = None
    source_agent: str
    created_at: dt.datetime
    at: dt.datetime
    read: bool
    read_at: dt.datetime | None = None


class NotificationListResponse(BaseModel):
    notifications: list[NotificationItemResponse] = Field(default_factory=list)
    unread_count: int = 0


class ParentChildResponse(BaseModel):
    usn: str
    name: str
    department: str
    year: int
    semester: int
    section: str
    relationship: str | None = None
    is_primary: bool | None = None
    mapping_id: int | None = None
    active: bool | None = None


class ParentProfileResponse(BaseModel):
    id: int
    name: str
    email: str | None = None
    mobile: str | None = None
    children: list[ParentChildResponse] = Field(default_factory=list)


class GeneratedCredentialsResponse(BaseModel):
    username: str
    temporary_password: str


class AdminParentResponse(BaseModel):
    id: int
    full_name: str
    username: str
    email: str | None = None
    mobile: str | None = None
    active: bool
    created_at: dt.datetime
    students: list[ParentChildResponse] = Field(default_factory=list)
    generated_credentials: GeneratedCredentialsResponse | None = None


class AdminParentListResponse(BaseModel):
    parents: list[AdminParentResponse] = Field(default_factory=list)
    total: int = 0


class ParentDashboardResponse(BaseModel):
    library: dict[str, Any] = Field(default_factory=dict)
    child: ParentChildResponse
    attendance: dict[str, Any] = Field(default_factory=dict)
    marks: dict[str, Any] = Field(default_factory=dict)
    fees: dict[str, Any] = Field(default_factory=dict)
    exams: dict[str, Any] = Field(default_factory=dict)
    timetable: dict[str, Any] = Field(default_factory=dict)
    scholarship: dict[str, Any] = Field(default_factory=dict)
    placements: list[dict[str, Any]] = Field(default_factory=list)
    events: list[dict[str, Any]] = Field(default_factory=list)


class ChatRoutingResponse(BaseModel):
    """Routing outcome; ``escalated`` is the legacy attempted-LLM flag."""
    tier: Literal["lexicon", "llm", "scope"]
    margin: float
    tau: float
    escalated: bool
    attempted_llm: bool = False
    accepted_llm: bool = False
    deterministic_fallback: bool = False
    reason: str
    fallback_from: str | None = None


class ChatToolUseResponse(BaseModel):
    name: str
    args: dict[str, Any] = Field(default_factory=dict)
    ms: float = 0.0


class ChatActionResponse(BaseModel):
    label: str
    route: str = Field(pattern=r"^/student/library(?:\?q=[^\s]*)?$")


class ChatLibraryContextBookResponse(BaseModel):
    title: str
    isbn: str
    author: str
    category: str


class ChatResponse(BaseModel):
    """Canonical read-only assistant result returned by ``POST /api/chat``."""
    text: str
    category: ChatCategory
    source_label: ChatSource
    context_topic: ChatTopic | None = None
    knowledge_sources: list[str] = Field(default_factory=list)
    mode: Literal["lexicon", "llm", "scope", "general_ai"]
    routing: ChatRoutingResponse
    tools_used: list[ChatToolUseResponse] = Field(default_factory=list)
    intent: str | None = None
    model: str | None = None
    provider: Literal["groq", "ollama"] | None = None
    latency_ms: float = 0.0
    fallback: bool = False
    fallback_code: str | None = None
    provenance: dict[str, Any] | None = None
    # Retained for compatibility with existing lexicon callers. It is always
    # the same authorized, read-only result used to produce ``text``.
    data: dict[str, Any] | None = None
    actions: list[ChatActionResponse] = Field(default_factory=list)
    # Safe public references only. Stock and other facts are always refreshed
    # server-side before a follow-up answer is produced.
    context_books: list[ChatLibraryContextBookResponse] = Field(default_factory=list)
    context_proof: str | None = Field(default=None, pattern=r"^[0-9a-f]{64}$")
    context_issued_at: int | None = Field(default=None, ge=0)


class AssistantRecordCapabilityResponse(BaseModel):
    category: str
    scope: str


class AssistantSuggestionGroupResponse(BaseModel):
    label: str
    prompts: list[str] = Field(default_factory=list)


class AssistantCapabilitiesResponse(BaseModel):
    """Display-safe assistant scope derived from backend authorization."""
    role: Literal["student", "faculty", "hod", "principal", "admin"]
    title: str
    subtitle: str
    description: str
    greeting: str
    help: str
    input_placeholder: str
    record_capabilities: list[AssistantRecordCapabilityResponse] = Field(default_factory=list)
    suggestion_groups: list[AssistantSuggestionGroupResponse] = Field(default_factory=list)
    ai_provider_mode: Literal["auto", "groq", "ollama", "disabled"] = "auto"
    ai_provider_status: str = "not_checked"
    ai_provider: Literal["groq", "ollama"] | None = None


class DepartmentAnalyticsResponse(BaseModel):
    dept: str
    students: int = 0
    faculty: int = 0
    shortage_students: int = 0
    avg_attendance: float = 0.0
    avg_cgpa: float = 0.0
    by_year: dict[int, int] = Field(default_factory=dict)


class DepartmentFeeCollectionResponse(BaseModel):
    due: float = 0.0
    collected: float = 0.0
    pct: float = 0.0


class FeeCollectionResponse(BaseModel):
    total_due: float = 0.0
    total_collected: float = 0.0
    total_outstanding: float = 0.0
    by_department: dict[str, DepartmentFeeCollectionResponse] = Field(
        default_factory=dict)


class PlacementStatsResponse(BaseModel):
    upcoming_drives: int = 0
    eligible_finalists: int = 0
    eligible_finalists_by_dept: dict[str, int] = Field(default_factory=dict)


class DepartmentAdmissionsResponse(BaseModel):
    intake: int = 0
    applications: int = 0
    allotted: int = 0


class AdmissionsFunnelResponse(BaseModel):
    stages: dict[str, int] = Field(default_factory=dict)
    departments: dict[str, DepartmentAdmissionsResponse] = Field(default_factory=dict)


class PrincipalAnalyticsResponse(BaseModel):
    departments: list[DepartmentAnalyticsResponse] = Field(default_factory=list)
    fee_collection: FeeCollectionResponse = Field(default_factory=FeeCollectionResponse)
    placements: PlacementStatsResponse = Field(default_factory=PlacementStatsResponse)
    admissions: AdmissionsFunnelResponse = Field(default_factory=AdmissionsFunnelResponse)


class AdmissionApplicationResponse(BaseModel):
    id: int
    applicant_name: str
    dept_code: str
    category: str
    tenth_pct: float
    twelfth_pct: float
    entrance_score: float
    status: str
    merit_score: float | None = None
    merit_rank: int | None = None
    allotted_usn: str | None = None
    notes: str = ""


class AdminAdmissionsResponse(BaseModel):
    funnel: AdmissionsFunnelResponse = Field(default_factory=AdmissionsFunnelResponse)
    applications: list[AdmissionApplicationResponse] = Field(default_factory=list)


class ScholarshipCriteriaRequest(BaseModel):
    minimum_cgpa: float | None = Field(None, ge=0, le=10)
    minimum_attendance: float | None = Field(None, ge=0, le=100)
    maximum_backlogs: int | None = Field(None, ge=0)
    fee_clearance_required: bool | None = None
    income_limit: float | None = Field(None, ge=0)
    allowed_departments: list[str] | None = None
    allowed_semesters: list[int] | None = None
    allowed_categories: list[str] | None = None
    required_documents: list[str] | None = None


class ScholarshipRequest(BaseModel):
    name: str = Field(min_length=2, max_length=160)
    provider: str = Field(min_length=2, max_length=160)
    description: str = Field(default="", max_length=5000)
    amount: float = Field(ge=0)
    application_url: str = Field(min_length=8, max_length=512)
    opens_at: dt.datetime
    closes_at: dt.datetime
    department_code: str = Field(min_length=2, max_length=8)
    official_document_reference: str = Field(default="", max_length=512)
    criteria: ScholarshipCriteriaRequest = Field(default_factory=ScholarshipCriteriaRequest)


class ScholarshipReviewRequest(BaseModel):
    comment: str = Field(default="", max_length=2000)


class ScholarshipApplyRequest(BaseModel):
    external_reference: str = Field(default="", max_length=256)
